import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import ToastProvider from "@/components/providers/toaster-provider";

const mhtirogla = localFont({
  src: "fonts/MHTIROGLA.ttf",
  variable: "--font-alt",
});

const neoPixel = localFont({
  src: "fonts/NEOPIXEL-Regular.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${neoPixel.className} ${mhtirogla.variable}`}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
